### ISSUE TITLE
Long popover title messes with layout

### ISSUE THREAD

**Issue by data-digger** [cocteauuk/thenude#10]
Take a look here:
https://beta.thenude.eu/model_index_a.html?page=2&affiliate_code_id=45
![image](https://cloud.githubusercontent.com/assets/1395675/24504243/c86c2f70-1555-11e7-8ec3-88ddde63790d.png)

Long title on a link may make the popover too wide. Ideally it should be the image container the one to control the final width of popover and the title should span multiple lines. Can we do it without JS?

Can we adjust this solution?
http://stackoverflow.com/questions/12747045/css-shrink-a-parent-div-to-fit-one-childs-width-and-constrain-the-width-of-th

**Comment by cocteauuk** [comment]
I took your suggestion. I think that works.

M

**Comment by data-digger** [comment]
Thanks, it looks fine
