### ISSUE TITLE
Center alphabet items in alphabet container 

### ISSUE THREAD

**Issue by data-digger** [cocteauuk/thenude#11]
Take a look here:
https://beta.thenude.eu/covers/fm-teens/a/

Sometimes not all letters will be displayed as there won't be any content for them. The list of items must be centered in the `<ul>` container. I tried to do it with text-align: center on `<ul class='alphabet'>` but due to float on `<li>` it doesn't work. Can we just remove the `float: left` on `<li>`'s? If it's there only to give width to it should still work due to `display: inline-block;`?

**Comment by cocteauuk** [comment]
Ok, I've applied `Display:flex` to this section. I tried using it in the calendar's years but it is not needed as we need the years to wrap. I reverted that last change.

**Comment by data-digger** [comment]
Thanks.

Fixed by f17cbb1c027e2106b33f571f9f5beffb9c2c02a2
