### ISSUE TITLE
carousel on model page: images with links

### ISSUE THREAD

**Issue by data-digger** [cocteauuk/thenude#12]
When I add a link to img in carousel the image loses its postioning - I'm not sure why as CSS properties seem too be the same for me. Take a look here:
https://beta.thenude.eu/Carmen%20Blue_12291.htm

**Comment by cocteauuk** [comment]
Fixed this.

**Comment by data-digger** [comment]
Fixed by bdf91376ccaf3c40ea048a72e93d9c1afe1b7dfe
