### ISSUE TITLE
[model page] Color on vote buttons

### ISSUE THREAD

**Issue by data-digger** [cocteauuk/thenude#13]
Sorry to bother you with this but I really suck when it comes to colors and design-ish stuff...

The red text on vote buttons on model page is barely visible, can we improve on it? It's very hard to read what it says.
https://beta.thenude.eu/Carmen%20Blue_12291.htm

**Comment by cocteauuk** [comment]
You're right, I think they actually look good in white, so I've removed the red styling.  They didn't need to get more attention anyway.

**Comment by data-digger** [comment]
Fixed by b4bfae5853ba26e7a64cf71fa8a05cd644bddbcd
