### ISSUE TITLE
Identify cover button

### ISSUE THREAD

**Issue by data-digger** [cocteauuk/thenude#16]
Take a look here:
https://www.thenude.eu/cover/harris-archives/3453/10-perfect-10s-by-ron-harris

There's a button when you move your mouse over the image. Clicking on it will show up the same modal dialog we have on unidentified page. Can you add the 'Identify' button to the cover? Ideally it would also work on cover listings.

**Comment by cocteauuk** [comment]
Created a couple of examples in the Model Finder Page. I think you should be ok applying the "thumb-box-overlay" class and items to a large image.

Let me know.

**Comment by data-digger** [comment]
Looks good, I think it can be merged to master? We'll be using the third solution (with the longest text) and the second one (the one on landscape cover - no text)
