### ISSUE TITLE
We need location telltale

### ISSUE THREAD

**Issue by data-digger** [cocteauuk/thenude#3]
We have a telltale to denote that we have a Google maps coordinates of shooting location:
https://www.thenude.eu/covers/erro-arch-movies/2006/05/
(note the mark in bottom right corner of cover image).

We need it too.

**Comment by cocteauuk** [comment]
Done, I've placed a map pin similar to the one you sent.

**Comment by data-digger** [comment]
Can we switch color on the telltale? I think current 'hover' color (i.e. #ff3600) should be used as base color - otherwise the telltale just isn't visible

**Comment by data-digger** [comment]
@cocteauuk Thanks. However this time the telltale is positioned in relation to image container, not the image itself. Due to margin on the cover img the telltale might be misaligned as seen here:
https://beta.thenude.eu/covers/metart/2017/04/
![image](https://cloud.githubusercontent.com/assets/1395675/24606045/a4c1a906-186b-11e7-9092-4421aea4b7a2.png)

**Comment by data-digger** [comment]
This must have been fixed along the way as the issue has disappeared.
