### ISSUE TITLE
Can we use flexbox to equalize height on model / cover listing?

### ISSUE THREAD

**Issue by data-digger** [cocteauuk/thenude#5]
On model-finder.html and in other places model / cover listing doesn't have equal height. According to ["the net" ](http://stackoverflow.com/a/22892773/760851) we possibly could use flexbox mode to fix it? Is it possible with our current layout without major rewrite?

Note:
I know we could use JavaScript to do it but I don't want to. Doing this using JS would cause layout trashing - something we want to avoid.

Note #2: We have < 1% usage share of < IE 11.

Example:
![image](https://cloud.githubusercontent.com/assets/1395675/24011506/44d673b2-0a7b-11e7-81be-293392dfcdfe.png)

**Comment by cocteauuk** [comment]
Ok, I've changed the rows to flex and changed the background color to fill the height of the column. Let me know if that wasn't what you meant.
