### ISSUE TITLE
Date of Birth on search.html

### ISSUE THREAD

**Issue by data-digger** [cocteauuk/thenude#6]
It's impossible to tell what 'Date of Birth' element does from user perspective - there's no indication that user can select there date of birth.

**Comment by data-digger** [comment]
Maybe we could use this? http://stackoverflow.com/questions/18146350/how-do-i-simulate-placeholder-functionality-on-input-date-field

**Comment by cocteauuk** [comment]
That seems to work, thanks. Updated.
