### ISSUE TITLE
Add background color to inactive background tabs on search.html

### ISSUE THREAD

**Issue by data-digger** [cocteauuk/thenude#7]
As in the title, here's an example:
![i83 cimgpsh_orig](https://cloud.githubusercontent.com/assets/1395675/24291565/c2710f6c-1089-11e7-9a29-37a980ce721f.png)

**Comment by cocteauuk** [comment]
Ok, Updating.

**Comment by data-digger** [comment]
Fixed in cc0af388baee5f3d6e7e84450d22f6ed829a102c
