### ISSUE TITLE
models.html screwed layout

### ISSUE THREAD

**Issue by data-digger** [cocteauuk/thenude#9]
Regarding 87cd9ae71db8d79e9370a64ac9c9be19396d6118, the `ul` doesn't clear float.

The bigger issue is that due to varying height of particular `li` elements the layout might go bad:
![image](https://cloud.githubusercontent.com/assets/1395675/24403554/b8265df0-13bd-11e7-85a2-522fe735d9a2.png)
Notice white space in first column second row. I think we'll need to equalize height of those items, at least per row (but I think it'll be fine if all `<li>s` in the `<ul>` will share single height. Maybe use`row--flex` - it seems to do the trick (I'm not absolutely sure if it's correct way of doing it though)

**Comment by cocteauuk** [comment]
Matt, could you send me a link to check this page live? Or tell me what is the bit of content that might be causing this. I need to replicate to see what's misbehaving. Thanks

**Comment by data-digger** [comment]
Fixed in cc0af388baee5f3d6e7e84450d22f6ed829a102c

**Comment by data-digger** [comment]
@cocteauuk I think I might have fixed it with usage of flex to equalize height. Can you check 03e1460 commit and confirm it?

**Comment by cocteauuk** [comment]
Hi Matt, please take a look at the changes, with this, if there are more content inside a particular <li> the other <li> items on the same line will inherit that height. Is this what you wanted?
